# Generated by Django 5.1.1 on 2024-09-22 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0005_profesor_profesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_coder.estudiante'),
        ),
    ]
